using System;

namespace WinuiWheaterForecastTray.Models;

/// <summary>
/// Represents current weather condition metrics and formatted UI strings.
/// </summary>
public class CurrentWeatherInfo
{
    /// <summary>Name of the geocoded city or location label.</summary>
    public string CityName { get; set; } = string.Empty;

    /// <summary>Formatted date string (e.g. "Friday, 31/07").</summary>
    public string DateString { get; set; } = string.Empty;

    /// <summary>Current temperature in degrees Celsius.</summary>
    public double Temperature { get; set; }

    /// <summary>Apparent ("feels like") temperature in degrees Celsius.</summary>
    public double ApparentTemperature { get; set; }

    /// <summary>WMO weather condition code.</summary>
    public int WeatherCode { get; set; }

    /// <summary>Localized weather condition description (e.g. "Sunny").</summary>
    public string ConditionText { get; set; } = string.Empty;

    /// <summary>Condition emoji icon (e.g. "☀️").</summary>
    public string Emoji { get; set; } = string.Empty;

    /// <summary>Relative humidity percentage (0–100 %).</summary>
    public double Humidity { get; set; }

    /// <summary>Wind speed in km/h.</summary>
    public double WindSpeed { get; set; }

    /// <summary>Cloud cover percentage (0–100 %).</summary>
    public double CloudCover { get; set; }

    /// <summary>Sea-level pressure (MSL) in hPa.</summary>
    public double Pressure { get; set; }

    /// <summary>Legacy alias for <see cref="Pressure"/>.</summary>
    [System.Obsolete("Use Pressure instead.")]
    public double SurfacePressure
    {
        get => Pressure;
        set => Pressure = value;
    }

    /// <summary>Precipitation probability for the current hour (0–100 %).</summary>
    public double PrecipitationProbability { get; set; }

    /// <summary>Localized air quality text description (e.g. "Good").</summary>
    public string AirQualityText { get; set; } = string.Empty;

    /// <summary>Localized UV index text description (e.g. "Moderate").</summary>
    public string UvIndexText { get; set; } = string.Empty;

    /// <summary>Sunrise time formatted as "HH:mm".</summary>
    public string SunriseTime { get; set; } = string.Empty;

    /// <summary>Sunset time formatted as "HH:mm".</summary>
    public string SunsetTime { get; set; } = string.Empty;

    /// <summary>Indicates whether current time is daytime.</summary>
    public bool IsDay { get; set; } = true;

    /// <summary>Optional custom formatted summary string generated by i18n service.</summary>
    public string? CustomSummaryText { get; set; }

    /// <summary>Formatted summary string for system tray tooltip or notification text.</summary>
    public string SummaryText => CustomSummaryText ?? $"📍 {CityName}\n{Emoji} {Math.Round(Temperature)}°C — {ConditionText}\n💧 {Math.Round(Humidity)}% humidity\n🌬️ {Math.Round(WindSpeed)} km/h wind";
}
